# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# Facebook
development:
  FACEBOOK_ID: 735195183192032
  FACEBOOK_SECRET: 3881d9a4b08c8b33e1d0d65902daa048
production:
  FACEBOOK_ID: 735195183192032
  FACEBOOK_SECRET: 3881d9a4b08c8b33e1d0d65902daa048
test:
  FACEBOOK_ID: 735195183192032
  FACEBOOK_SECRET: 3881d9a4b08c8b33e1d0d65902daa048

#Twitter
development:
  TWITTER_KEY: 0g52aLxcSy8O2YWjJ12dQ
  TWITTER_SECRET: BFOjonGmzBTQFJGsl76Yj8SzQ08RR3aj7iZyiYQFQiY
  TWITTER_TOKEN: 176554524-RSFRZdk15Q3BnyTBfLLTYMJvD4QWHSduWG0okgOa
  TWITTER_TOKEN_SECRET: E72edSlBDzVMQb4ySNyjydsCyCUOSGbHp5DwumwwzYzKS
test:
  TWITTER_KEY: 0g52aLxcSy8O2YWjJ12dQ
  TWITTER_SECRET: BFOjonGmzBTQFJGsl76Yj8SzQ08RR3aj7iZyiYQFQiY
  TWITTER_TOKEN: 176554524-RSFRZdk15Q3BnyTBfLLTYMJvD4QWHSduWG0okgOa
  TWITTER_TOKEN_SECRET: E72edSlBDzVMQb4ySNyjydsCyCUOSGbHp5DwumwwzYzKS
production:
  TWITTER_KEY: 0g52aLxcSy8O2YWjJ12dQ
  TWITTER_SECRET: BFOjonGmzBTQFJGsl76Yj8SzQ08RR3aj7iZyiYQFQiY
  TWITTER_TOKEN: 176554524-RSFRZdk15Q3BnyTBfLLTYMJvD4QWHSduWG0okgOa
  TWITTER_TOKEN_SECRET: E72edSlBDzVMQb4ySNyjydsCyCUOSGbHp5DwumwwzYzKS
