TWITTER_CONSUMER_KEY: 0g52aLxcSy8O2YWjJ12dQ
TWITTER_CONSUMER_SECRET: BFOjonGmzBTQFJGsl76Yj8SzQ08RR3aj7iZyiYQFQiY
TWITTER_ACCESS_TOKEN: 176554524-RSFRZdk15Q3BnyTBfLLTYMJvD4QWHSduWG0okgOa
TWITTER_ACCESS_TOKEN_SECRET: E72edSlBDzVMQb4ySNyjydsCyCUOSGbHp5DwumwwzYzKS

SQUARE_ID: vhchNrfOibzXceotU3fXKA
SQUARE_SECRET: earDav9cL41rvrMViA2p0sr0Rma02eHITI7BYvE3L9M
SQUARE_ACCESS_TOKEN: UMXFIRP_MsgBwKTwai61xw
